"""Test Hard Part 8: Real Artifacts (PDF & PPTX).
A proper GST invoice (PDF) and a business-analysis deck (PPTX) with real charts
generated by the agent's own tools, not screenshots or plain text.
"""

import os
import unittest
from pathlib import Path
from src.database.seed import seed_database
from src.generators.invoice_pdf import generate_gst_invoice_pdf
from src.generators.analysis_pptx import generate_weekly_analysis_pptx
from src.skills.billing_skill import add_or_update_cart, finalize_bill


class TestArtifacts(unittest.TestCase):

    def setUp(self):
        seed_database(reset=True)
        self.session_id = "test_artifact_session"

    def test_pdf_invoice_generation(self):
        """Generates a valid GST tax invoice PDF with positive byte size."""
        add_or_update_cart(
            session_id=self.session_id,
            items=[
                {"item_name": "Sugar (loose)", "quantity": 2.0},
                {"item_name": "Maggi 70g", "quantity": 4.0}
            ],
            payment_mode="UPI"
        )
        fin = finalize_bill(session_id=self.session_id, generate_pdf=True)
        pdf_path = fin.get("invoice_pdf_path")
        self.assertIsNotNone(pdf_path)
        self.assertTrue(Path(pdf_path).exists())
        self.assertGreater(os.path.getsize(pdf_path), 200)

        # Check PDF header
        with open(pdf_path, "rb") as f:
            header = f.read(4)
            self.assertEqual(header, b"%PDF")

    def test_pptx_analysis_deck_generation(self):
        """Generates an executive analysis presentation file with positive byte size."""
        data = {
            "total_sales": 15420.0,
            "total_gst": 1850.40,
            "total_bills": 42,
            "payment_split": {"UPI": 10200.0, "CASH": 4220.0, "KHATA": 1000.0},
            "top_items": [
                {"name": "Aashirvaad Atta 5kg", "revenue": 4125.0, "quantity": 15},
                {"name": "Maggi 70g", "revenue": 1400.0, "quantity": 100},
            ],
            "low_stock_items": [
                {"name": "Surf Excel 1kg", "stock": 3, "reorder": 5, "unit": "packet", "status": "LOW"}
            ]
        }
        pptx_path = generate_weekly_analysis_pptx(data)
        self.assertIsNotNone(pptx_path)
        self.assertTrue(Path(pptx_path).exists())
        self.assertGreater(os.path.getsize(pptx_path), 200)


if __name__ == "__main__":
    unittest.main()
